baseurl = "0xbhsu.github.io"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "0xbhsu"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/posts/:year/:month/:day/:slug/"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2
[[menu.right]]
name = "About"
url = "/about/"
weight = 3

[params]
custom_css = ["css/theme-override.css"]
description = "0xbhsu's blog."